<?php

namespace MillenniumFalcon\Core\ORM;

use MillenniumFalcon\Core\ORM\Traits\AssetSizeTrait;
use Symfony\Component\Validator\Constraints as Assert;

class AssetSize extends \MillenniumFalcon\Core\ORM\Generated\AssetSize
{
    use AssetSizeTrait;

    /** @Assert\Positive  */
    public function getWidth(): int
    {
        return (int) parent::getWidth(); // TODO: Change the autogenerated stub
    }

    public function setWidth($width): void
    {
        parent::setWidth((int)$width); // TODO: Change the autogenerated stub
    }

}
