<?php

namespace MillenniumFalcon\Core\ORM;

use MillenniumFalcon\Core\ORM\Traits\AssetTrait;
use Symfony\Component\Validator\Constraints as Assert;

class Asset extends \MillenniumFalcon\Core\ORM\Generated\Asset
{
    use AssetTrait;

    /** @Assert\PositiveOrZero() */
    public function getWidth(): int
    {
        return (int) parent::getWidth(); // TODO: Change the autogenerated stub
    }

    public function setWidth($width): void
    {
        parent::setWidth((int)$width); // TODO: Change the autogenerated stub
    }

    /** @Assert\PositiveOrZero() */
    public function getHeight(): int
    {
        return (int) parent::getHeight(); // TODO: Change the autogenerated stub
    }

    public function setHeight($height): void
    {
        parent::setHeight((int)$height); // TODO: Change the autogenerated stub
    }

}
