<?php

namespace MillenniumFalcon\Core\Orm\Traits;

use MillenniumFalcon\Core\Nestable\NodeInterface;
use MillenniumFalcon\Core\Orm\PageTemplate;

trait PageTrait
{
    /**
     * @var array
     */
    private $children = array();

    /**
     * @return array
     */
    public function getChildren(): array
    {
        return $this->children;
    }

    /**
     * @param array $children
     */
    public function setChildren(array $children)
    {
        $this->children = $children;
    }

    /**
     * @param NodeInterface $child
     */
    public function addChild(NodeInterface $child)
    {
        $this->children[] = $child;
    }

    /**
     * @return string
     */
    public function getIcon()
    {
        return '';
    }

    /**
     * @return mixed|null|string
     */
    public function getTemplate()
    {
        return $this->objPageTempalte()->getFilename(); // TODO: Change the autogenerated stub
    }

    /**
     * @return PageTemplate|null
     */
    public function objPageTempalte()
    {
        /** @var PageTemplate $pageTemplate */
        $pageTemplate = PageTemplate::getById($this->getPdo(), $this->getTemplateFile());
        return $pageTemplate;
    }

    /**
     * @return mixed
     */
    public function objContent()
    {
        return json_decode($this->getContent());
    }

    /**
     * @return string
     */
    static public function getCmsOrmsTwig()
    {
        return 'cms/orms/orms-custom-pages.html.twig';
    }
}